from cloud_inquisitor.exceptions import InquisitorError


class ResourceKillError(InquisitorError):
    pass


class ResourceStopError(InquisitorError):
    pass
